# pyrefly: ignore [missing-import]
from docx import Document
# pyrefly: ignore [missing-import]
from docx.shared import Pt, RGBColor, Inches, Cm
# pyrefly: ignore [missing-import]
from docx.enum.text import WD_ALIGN_PARAGRAPH
# pyrefly: ignore [missing-import]
from docx.oxml.ns import qn
# pyrefly: ignore [missing-import]
from docx.oxml import OxmlElement
import datetime
import os


def set_heading_color(paragraph, hex_color="4F46E5"):
    for run in paragraph.runs:
        run.font.color.rgb = RGBColor(
            int(hex_color[0:2], 16),
            int(hex_color[2:4], 16),
            int(hex_color[4:6], 16)
        )


def add_page_number(paragraph):
    run = paragraph.add_run()
    fldChar1 = OxmlElement('w:fldChar')
    fldChar1.set(qn('w:fldCharType'), 'begin')
    instrText = OxmlElement('w:instrText')
    instrText.text = 'PAGE'
    fldChar2 = OxmlElement('w:fldChar')
    fldChar2.set(qn('w:fldCharType'), 'end')
    run._r.append(fldChar1)
    run._r.append(instrText)
    run._r.append(fldChar2)


def generate_docx(book_title: str, segments, output_dir: str = "output") -> str:
    os.makedirs(output_dir, exist_ok=True)
    safe_title = "".join(c for c in book_title if c.isalnum() or c in (" ", "-", "_")).strip()
    filepath   = os.path.join(output_dir, f"{safe_title}.docx")

    doc = Document()

    # ── Page Setup ─────────────────────────────────────────────────────────────
    section = doc.sections[0]
    section.page_height     = Cm(29.7)
    section.page_width      = Cm(21.0)
    section.left_margin     = Cm(2.5)
    section.right_margin    = Cm(2.5)
    section.top_margin      = Cm(2.5)
    section.bottom_margin   = Cm(2.0)

    # ── Default styles ─────────────────────────────────────────────────────────
    style_normal = doc.styles['Normal']
    style_normal.font.name = 'Calibri'
    style_normal.font.size = Pt(11)

    # ══════════════════════════════════════════════════════════════════════════
    # COVER PAGE
    # ══════════════════════════════════════════════════════════════════════════
    doc.add_paragraph()
    doc.add_paragraph()
    doc.add_paragraph()

    title_para = doc.add_paragraph()
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_run  = title_para.add_run(book_title)
    title_run.font.size  = Pt(28)
    title_run.font.bold  = True
    title_run.font.color.rgb = RGBColor(0x1E, 0x29, 0x3B)

    doc.add_paragraph()

    date_para = doc.add_paragraph()
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    date_run  = date_para.add_run(f"Generated on {datetime.date.today().strftime('%B %d, %Y')}")
    date_run.font.size  = Pt(12)
    date_run.font.color.rgb = RGBColor(0x64, 0x74, 0x8B)

    doc.add_paragraph()
    agent_para = doc.add_paragraph()
    agent_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    agent_run  = agent_para.add_run("Generated by AI Book Writing Agent")
    agent_run.font.size  = Pt(10)
    agent_run.font.italic = True
    agent_run.font.color.rgb = RGBColor(0x94, 0xA3, 0xB8)

    doc.add_page_break()

    # ══════════════════════════════════════════════════════════════════════════
    # TABLE OF CONTENTS
    # ══════════════════════════════════════════════════════════════════════════
    toc_heading = doc.add_heading("Table of Contents", level=1)
    set_heading_color(toc_heading, "1E293B")

    chapters = {}
    for seg in segments:
        key = seg.chapter_number
        if key not in chapters:
            chapters[key] = {"title": seg.chapter_title, "subs": []}
        chapters[key]["subs"].append(seg.subheading)

    for ch_num in sorted(chapters.keys()):
        ch   = chapters[ch_num]
        para = doc.add_paragraph(style='List Bullet')
        run  = para.add_run(f"Chapter {ch_num}  —  {ch['title']}")
        run.font.bold = True
        run.font.size = Pt(11)
        run.font.color.rgb = RGBColor(0x4F, 0x46, 0xE5)
        for sub in ch["subs"]:
            sub_para = doc.add_paragraph(style='List Bullet 2')
            sub_run  = sub_para.add_run(sub)
            sub_run.font.size = Pt(10)
            sub_run.font.color.rgb = RGBColor(0x64, 0x74, 0x8B)

    doc.add_page_break()

    # ══════════════════════════════════════════════════════════════════════════
    # CHAPTERS
    # ══════════════════════════════════════════════════════════════════════════
    current_chapter = None

    for seg in segments:
        if seg.chapter_number != current_chapter:
            if current_chapter is not None:
                doc.add_page_break()
            current_chapter = seg.chapter_number

            # Chapter label
            label_para = doc.add_paragraph()
            label_run  = label_para.add_run(f"Chapter {seg.chapter_number}")
            label_run.font.size  = Pt(11)
            label_run.font.color.rgb = RGBColor(0x4F, 0x46, 0xE5)
            label_run.font.bold  = True

            # Chapter title
            ch_heading = doc.add_heading(seg.chapter_title, level=1)
            set_heading_color(ch_heading, "1E293B")
            doc.add_paragraph()

        # Sub-heading
        sub_heading = doc.add_heading(seg.subheading, level=2)
        set_heading_color(sub_heading, "334155")

        # Body content
        for para_text in seg.content.split("\n"):
            para_text = para_text.strip()
            if para_text:
                para = doc.add_paragraph(para_text)
                para.style = doc.styles['Normal']
                para.paragraph_format.space_after  = Pt(6)
                para.paragraph_format.line_spacing = Pt(16)
                para.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY

    # ── Save ───────────────────────────────────────────────────────────────────
    doc.save(filepath)
    print(f"  ✅ DOCX saved: {filepath}")
    return filepath
