from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak,
    HRFlowable, Table, TableStyle
)
from reportlab.lib.colors import HexColor, white
from reportlab.lib import colors
import datetime
import os

# ── Colours ───────────────────────────────────────────────────────────────────
DARK   = HexColor("#1E293B")
ACCENT = HexColor("#4F46E5")
GRAY   = HexColor("#64748B")
LGRAY  = HexColor("#F1F5F9")

def S(name, **kw):
    return ParagraphStyle(name, **kw)

PAGE_W, PAGE_H = A4
MARGIN = 22 * mm

# ── Page number callback ───────────────────────────────────────────────────────
class PageNumCanvas:
    def __init__(self, canvas, doc):
        self.canvas = canvas
        self.doc    = doc

def on_later_page(canvas, doc):
    w, h = A4
    canvas.saveState()
    canvas.setFillColor(DARK)
    canvas.rect(0, 0, w, 10*mm, fill=1, stroke=0)
    canvas.setFillColor(white)
    canvas.setFont("Helvetica", 8)
    canvas.drawString(MARGIN, 3.5*mm, doc.title)
    canvas.drawRightString(w - MARGIN, 3.5*mm, f"Page {doc.page}")
    canvas.restoreState()

def on_first_page(canvas, doc):
    pass  # cover handles itself


def generate_pdf(book_title: str, segments, output_dir: str = "output") -> str:
    os.makedirs(output_dir, exist_ok=True)
    safe_title = "".join(c for c in book_title if c.isalnum() or c in (" ", "-", "_")).strip()
    filepath   = os.path.join(output_dir, f"{safe_title}.pdf")

    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        leftMargin=MARGIN, rightMargin=MARGIN,
        topMargin=MARGIN,  bottomMargin=18*mm,
        title=book_title,
    )
    doc.title = book_title

    # ── Styles ─────────────────────────────────────────────────────────────────
    cover_title  = S("ct",  fontName="Helvetica-Bold", fontSize=32, textColor=white,
                     leading=40, alignment=TA_CENTER, spaceAfter=8)
    cover_sub    = S("cs",  fontName="Helvetica",      fontSize=13, textColor=HexColor("#CBD5E1"),
                     leading=18, alignment=TA_CENTER)
    toc_item     = S("ti",  fontName="Helvetica",      fontSize=10, textColor=DARK,
                     leading=16, leftIndent=0, spaceAfter=3)
    toc_sub      = S("tsi", fontName="Helvetica",      fontSize=9,  textColor=GRAY,
                     leading=14, leftIndent=14, spaceAfter=2)
    ch_label     = S("cl",  fontName="Helvetica",      fontSize=11, textColor=ACCENT,
                     leading=16, spaceBefore=0, spaceAfter=4)
    ch_title     = S("cht", fontName="Helvetica-Bold", fontSize=22, textColor=DARK,
                     leading=28, spaceBefore=4, spaceAfter=6)
    sub_style    = S("ss",  fontName="Helvetica-Bold", fontSize=13, textColor=DARK,
                     leading=18, spaceBefore=14, spaceAfter=5)
    body_style   = S("bs",  fontName="Helvetica",      fontSize=10.5, textColor=HexColor("#334155"),
                     leading=17, spaceAfter=8, alignment=TA_JUSTIFY)
    story = []

    # ══════════════════════════════════════════════════════════════════════════
    # COVER PAGE
    # ══════════════════════════════════════════════════════════════════════════
    def cover_page(canvas, doc):
        w, h = A4
        # dark background
        canvas.setFillColor(DARK)
        canvas.rect(0, 0, w, h, fill=1, stroke=0)
        # accent bar
        canvas.setFillColor(ACCENT)
        canvas.rect(0, h * 0.38, w, 4, fill=1, stroke=0)
        canvas.rect(0, h * 0.38 - 10, w, 2, fill=1, stroke=0)
        # footer bar
        canvas.setFillColor(HexColor("#0F172A"))
        canvas.rect(0, 0, w, 20*mm, fill=1, stroke=0)
        canvas.setFillColor(HexColor("#475569"))
        canvas.setFont("Helvetica", 9)
        canvas.drawCentredString(w/2, 8*mm, f"Generated by AI Book Agent  ·  {datetime.date.today()}")

    story.append(Spacer(1, 55*mm))
    story.append(Paragraph(book_title, cover_title))
    story.append(Spacer(1, 6*mm))
    story.append(Paragraph(f"Generated on {datetime.date.today().strftime('%B %d, %Y')}", cover_sub))
    story.append(PageBreak())

    # ══════════════════════════════════════════════════════════════════════════
    # TABLE OF CONTENTS
    # ══════════════════════════════════════════════════════════════════════════
    story.append(Spacer(1, 8*mm))
    story.append(Paragraph("Table of Contents", S("toch", fontName="Helvetica-Bold",
                 fontSize=20, textColor=DARK, leading=26, spaceAfter=8)))
    story.append(HRFlowable(width="100%", thickness=2, color=ACCENT, spaceAfter=8))

    # Group segments by chapter
    chapters = {}
    for seg in segments:
        key = seg.chapter_number
        if key not in chapters:
            chapters[key] = {"title": seg.chapter_title, "subs": []}
        chapters[key]["subs"].append(seg.subheading)

    for ch_num in sorted(chapters.keys()):
        ch = chapters[ch_num]
        story.append(Paragraph(
            f"<b>Chapter {ch_num}</b>  —  {ch['title']}", toc_item))
        for sub in ch["subs"]:
            story.append(Paragraph(f"• {sub}", toc_sub))
        story.append(Spacer(1, 4))

    story.append(PageBreak())

    # ══════════════════════════════════════════════════════════════════════════
    # CHAPTERS
    # ══════════════════════════════════════════════════════════════════════════
    current_chapter = None

    for seg in segments:
        # New chapter — add chapter heading page break
        if seg.chapter_number != current_chapter:
            if current_chapter is not None:
                story.append(PageBreak())
            current_chapter = seg.chapter_number

            story.append(Spacer(1, 10*mm))
            story.append(Paragraph(f"Chapter {seg.chapter_number}", ch_label))
            story.append(Paragraph(seg.chapter_title, ch_title))
            story.append(HRFlowable(width="100%", thickness=1.5,
                                    color=ACCENT, spaceAfter=10))

        # Sub-heading
        story.append(Paragraph(seg.subheading, sub_style))

        # Body content — split into paragraphs
        for para in seg.content.split("\n"):
            para = para.strip()
            if para:
                story.append(Paragraph(para, body_style))

    # ── Build ──────────────────────────────────────────────────────────────────
    doc.build(story, onFirstPage=cover_page, onLaterPages=on_later_page)
    print(f"  ✅ PDF saved: {filepath}")
    return filepath
